[build]
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"

[build.processing]
skip_processing = false

[build.processing.html]
pretty_urls = true

[build.processing.static]
chunking = true
compress = true

[build.processing.images]
compress = true